# Regenerates `crates/ldac-sys/src/bindings.rs` from the pinned `ldacBT` header and proves
# the checked-in file still matches.
#
# This check earns its place more than most. A wrong FFI signature here links fine and is
# wrong *silently*: `ldacBT_init_handle_decode` takes six ints, three of which are reserved,
# and getting the arity or the order wrong produces a handle that decodes noise rather than
# an error. Nothing at build time would catch it — the crate declares the functions itself,
# so there is no header for a compiler to disagree with (#14).
#
# The header comes from the `ldacbt` derivation rather than from `pkgs.ldacbt` or from the
# source tarball directly, so it is by construction the header belonging to the *same*
# `libldacBT.so` that `ldac-sys` links. Under the flake's nixpkgs pin those are not the same
# thing at all: `pkgs.ldacbt` is an encoder-only build whose header does not declare
# `ldacBT_decode` (see nix/ldacbt.nix), and generating bindings from it would produce a file
# that compiles and is missing the entire decode API.
{ pkgs, rustToolchain, ldacbt }:

let
  bindings = ../crates/ldac-sys/src/bindings.rs;
  rustfmtToml = ../rustfmt.toml;

  # Kept in sync with the preamble in the checked-in file by construction: this is what
  # writes it. The version is baked in, so bumping the pinned source fails this check with
  # a one-line diff naming the new version rather than passing quietly on an ABI nobody
  # re-read.
  preamble = ''
    /* automatically generated by rust-bindgen ${pkgs.rust-bindgen.version} */

    // Generated by bindgen from inc/ldacBT.h in ldacBT ${ldacbt.version}
    // (open-vela/external_libldac, Sony's own library — see nix/ldacbt.nix).
    // Regenerate via the `ldac-bindings` flake check; do not edit by hand.
    #![allow(
        non_upper_case_globals,
        non_camel_case_types,
        non_snake_case,
        unsafe_code,
        clippy::all,
        clippy::pedantic
    )]
  '';
in
pkgs.runCommand "ldac-bindings"
{
  nativeBuildInputs = [ pkgs.rust-bindgen rustToolchain ];
  inherit bindings rustfmtToml preamble;
  header = "${ldacbt}/include/ldacBT.h";
} ''
  set -euo pipefail

  echo "regenerating ldac-sys bindings from ldacBT ${ldacbt.version}"

  # The allowlist is the whole `ldacBT_*` surface plus the constants a caller needs to pass
  # it legal arguments — the channel modes, the sample formats, and the error codes the
  # wrapper matches on. The encoder comes along because the LDAC test fixtures are
  # generated with it (`pipeline/examples/ldac_fixtures.rs`); nothing in the receiver calls
  # it.
  #
  # `--rustified-enum LDACBT_SMPL_FMT_T` so an illegal sample format is unrepresentable at
  # the call (ground rule 1). `_bindgen_ty_1` is the anonymous EQMID enum, constified
  # because an anonymous type name would leak bindgen's numbering into our source.
  #
  # Not generated, and therefore the one hand-written part of the crate: the error-code
  # macros. They are function-like `#define`s and bindgen emits nothing for them; see
  # `ldac_sys::err`.
  bindgen \
    --allowlist-function 'ldacBT_.*' --allowlist-type 'LDACBT_SMPL_FMT_T' \
    --allowlist-var 'LDACBT_.*|LDAC_CCI_.*' \
    --rustified-enum 'LDACBT_SMPL_FMT_T' --constified-enum '_bindgen_ty_1' \
    --no-layout-tests --no-doc-comments \
    --formatter=none \
    "$header" -- -std=c99 \
    | tail -n +2 > body.rs

  # A header built `_ENCODE_ONLY` still generates a perfectly valid file, just without the
  # two functions the receiver exists to call. Fail on that here rather than at link time.
  grep -q 'fn ldacBT_decode' body.rs || {
    echo "ERROR: the pinned header declares no ldacBT_decode." >&2
    echo "That means the ldacbt derivation was built _ENCODE_ONLY — see nix/ldacbt.nix." >&2
    exit 1
  }

  # `--formatter=none` above, then the project's own rustfmt, so the result is both
  # reproducible and `cargo fmt`-clean. Letting bindgen invoke rustfmt itself would pick up
  # whatever config happened to be in the working directory.
  { printf '%s\n' "$preamble"; cat body.rs; } > generated.rs
  cp "$rustfmtToml" rustfmt.toml
  rustfmt --edition 2021 generated.rs

  if ! diff -u "$bindings" generated.rs; then
    echo "" >&2
    echo "ERROR: crates/ldac-sys/src/bindings.rs is stale." >&2
    echo "The pinned ldacBT header no longer matches the checked-in bindings." >&2
    echo "Read the diff above before accepting it: this is an ABI change to a" >&2
    echo "library whose signatures nothing else in the build checks, so a wrong" >&2
    echo "one decodes noise instead of failing." >&2
    exit 1
  fi

  echo "bindings match the pinned ldacBT header"
  touch $out
''
