# Regenerates `crates/moonlight-sys/src/bindings.rs` from the pinned `Limelight.h` and
# proves the checked-in file still matches.
#
# The sibling of `nix/ldac-bindings.nix`, and it guards a different failure. `ldac-sys`
# declares its own signatures, so there is no header for a compiler to disagree with.
# `moonlight-sys` does have one — and the generated file's own layout assertions
# (`["Size of _STREAM_CONFIGURATION"][size_of::<…>() - 80usize]`) look like they cover
# this. They do not: bindgen produced both the struct and the assertion from the same
# header, so they are self-referential. They catch a hand-edit and a target-ABI change,
# and they cannot catch *upstream* drift, because a revision bump that changed the layout
# would change neither the struct nor the assertion in the checked-in file — it would
# change only the library the struct is passed to.
#
# So the failure this closes is: bump the rev in flake.nix, get a `STREAM_CONFIGURATION`
# with a field inserted in the middle, and hand a live session parameters read from the
# wrong offsets. Nothing at build time, nothing at link time, and a stream that negotiates
# and then behaves oddly (#191).
#
# The header comes from the `moonlight-common-c` derivation, so it is by construction the
# header belonging to the same `libmoonlight-common-c.a` the crate links.
{ pkgs, rustToolchain, moonlightCommonC }:

let
  bindings = ../crates/moonlight-sys/src/bindings.rs;
  rustfmtToml = ../rustfmt.toml;

  # The pinned revision, baked into the preamble by the same command that writes the file.
  # A revision bump therefore fails this check with a diff whose *first* hunk names the new
  # rev, rather than passing quietly on an ABI nobody re-read.
  rev = moonlightCommonC.src.rev or "pinned";

  preamble = ''
    /* automatically generated by rust-bindgen ${pkgs.rust-bindgen.version} */

    // Generated by bindgen from moonlight-common-c src/Limelight.h
    // rev ${rev} — see nix/moonlight-common-c.nix.
    // Regenerate via the `moonlight-bindings` flake check; do not edit by hand.
    #![allow(
        non_upper_case_globals,
        non_camel_case_types,
        non_snake_case,
        unsafe_code,
        clippy::all,
        clippy::pedantic
    )]
  '';
in
pkgs.runCommand "moonlight-bindings"
{
  nativeBuildInputs = [ pkgs.rust-bindgen rustToolchain ];
  inherit bindings rustfmtToml preamble;
  header = "${moonlightCommonC}/include/Limelight.h";
} ''
  set -euo pipefail

  echo "regenerating moonlight-sys bindings from Limelight.h rev ${rev}"

  # `--allowlist-file` rather than a name allowlist: Limelight.h is the entire public
  # surface and the crate re-exports all of it, so the boundary that matters is "declared
  # in this header" — which also keeps <stdint.h>'s several hundred glibc constants out.
  #
  # `--default-macro-constant-type signed` because the header's `#define`s are used as
  # `c_int` arguments (`VIDEO_FORMAT_H264`, `ENCFLG_*`, the `AUDIO_CONFIGURATION_*` set).
  # Unsigned would make every call site cast.
  #
  # Layout tests are deliberately *left on*, unlike `ldac-bindings`. They are
  # self-referential against upstream drift, which is what this check is for — but they
  # still catch the two things they can catch, and one of those (a target ABI where the
  # struct lays out differently) is live here because the tree cross-builds to Windows.
  bindgen \
    --allowlist-file '.*/Limelight\.h' \
    --default-macro-constant-type signed \
    --no-doc-comments \
    --formatter=none \
    "$header" -- -std=c99 \
    | tail -n +2 > body.rs

  # The symbol the whole carve-out exists for. A header that generated cleanly and
  # declares no `LiStartConnection` is not a header for this library.
  grep -q 'fn LiStartConnection' body.rs || {
    echo "ERROR: the pinned header declares no LiStartConnection." >&2
    echo "That is not moonlight-common-c's Limelight.h — check nix/moonlight-common-c.nix." >&2
    exit 1
  }

  # `--formatter=none` above, then the project's own rustfmt, so the result is both
  # reproducible and `cargo fmt`-clean. Letting bindgen invoke rustfmt itself would pick up
  # whatever config happened to be in the working directory.
  { printf '%s\n' "$preamble"; cat body.rs; } > generated.rs
  cp "$rustfmtToml" rustfmt.toml
  rustfmt --edition 2021 generated.rs

  if ! diff -u "$bindings" generated.rs; then
    echo "" >&2
    echo "ERROR: crates/moonlight-sys/src/bindings.rs is stale." >&2
    echo "The pinned Limelight.h no longer matches the checked-in bindings." >&2
    echo "Read the diff above before accepting it. A layout change here is not a" >&2
    echo "compile error and not a link error: it is a live session handed its" >&2
    echo "parameters from the wrong offsets. See D37 for why this library is linked" >&2
    echo "rather than reimplemented, and what that costs." >&2
    exit 1
  fi

  echo "bindings match the pinned Limelight.h"
  touch $out
''
