# The auto-update loop from a staged tree onwards, in a VM (#345).
#
# **What this cannot cover, and why, stated first because it used to.** The receiver now
# requires GitHub build provenance — a Sigstore bundle signed by a certificate Fulcio
# issued to this repository's release workflow (D59). A fake release API cannot mint one;
# that would need a fake Fulcio and a fake Rekor. So the fetch-and-verify leg is covered by
# `castaway_update::attestation`'s unit tests, which check a *real* bundle for a *real*
# release of this repository against the real trust root, offline.
#
# What is left here is still most of the machine, and none of it is reachable by a unit
# test: a real launcher supervising real processes, the rediscovery of a tree staged on a
# night the panel never went quiet, the idle policy against the *shipped* window, the
# handshake exit, the launcher restarting into the new tree, the health marker, and the
# version GC keeping the rollback target.
#
# **What this does not cover, second: the manual check (#360).** Its only trigger is a
# press on the settings screen, and this VM has no glass — the agent's `Handle` is held by
# a `Setting` that only exists in a rendering build, and nothing reaches it from a shell.
# Adding a back door so the VM could pull it would be testing the back door. So the manual
# path is covered where it is genuinely reachable instead: `castaway_update::policy` for
# what a manual request skips, and `castaway_update::agent`'s tests for the command
# channel — against a fake release API serving the *real* attested manifest, so the
# offer, the up-to-date answer, the already-staged answer, the `hold` refusal and the
# serialisation of a request arriving mid-look all run the whole trust path.
#
# Two builds, not one, and that is what makes the ordering real: the running receiver is
# stamped build 100 and the staged one 101, so `Offer::Newer` is a fact about the binaries
# rather than something the test asserted into existence.
{ pkgs, castaway, launcher, releaseManifest }:

let
  # Two versions. Forty hex characters because that is what a `VersionId` is, and visibly
  # patterned because a failure message full of shas is unreadable otherwise.
  shaA = "a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1";
  shaB = "b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2";
  shortB = builtins.substring 0 7 shaB;
  buildA = 100;
  buildB = 101;

  # A receiver that knows which build it is. Overriding the package rather than adding a
  # feature: `CASTAWAY_BUILD` is already a build-time input of every real artifact, so this
  # configures the same knob the release build uses (D55 — nothing here is a compile-time
  # gate on behaviour).
  #
  # Nothing overrides the *trust anchors*: both receivers carry the ones this tree ships,
  # because the point of the rediscovery path is that a staged tree needs no verification —
  # it was verified when it was staged, which is why it was named.
  receiver = { build, rev }: castaway.overrideAttrs (_: {
    CASTAWAY_BUILD = toString build;
    CASTAWAY_GIT_REV = rev;
  });
  receiverA = receiver { build = buildA; rev = builtins.substring 0 7 shaA; };
  receiverB = receiver { build = buildB; rev = shortB; };

  # A staged version, exactly as `Agent::stage` leaves one: the tree under its final name,
  # with the manifest that describes it written inside. That manifest is what
  # `rediscover_staged` reads at boot to conclude a newer version is already waiting — the
  # real path for an update that finished downloading on a night the panel stayed busy.
  #
  # Generated by the *real* release script, so the JSON this test relies on is the JSON CI
  # produces rather than a hand-written lookalike.
  stagedManifest = pkgs.runCommand "castaway-staged-manifest"
    { nativeBuildInputs = [ releaseManifest pkgs.coreutils ]; } ''
    # The manifest's digest and size describe the artifact a real staging downloaded. Only
    # `build` is read back here, but it has to be a manifest that parses, so it is made
    # from a real file rather than faked.
    printf 'a staged artifact' > castaway-portable-${shortB}.zip
    castaway-release-manifest castaway-portable-${shortB}.zip ${shaB} ${toString buildB} out
    mkdir -p "$out" && cp out/manifest.json "$out/"
  '';

  # The panel's config. The window is the *shipped* one — the test moves the guest's clock
  # into it rather than widening it, so what runs here is the schedule that ships.
  config = pkgs.writeText "castaway.toml" ''
    friendly_name = "castaway-update-vm"
    http_port = 8080

    [log]
    # The updater's "Latest is not newer" line is `debug` — it is the ordinary answer on
    # every night after the first, and an unattended panel should not narrate those at
    # `info`. The test asserts on it, so the console filter has to carry it.
    level = "info,castaway_update=debug"
    to_file = false

    [update]
    enable = true
    # Unreachable on purpose: nothing in this test should be fetching a release. If the
    # updater ever *does* reach the network here, the check that follows would be testing
    # something other than what it claims.
    base_url = "http://127.0.0.1:9"
    repository = "schlarpc/castaway"
    window_start = "03:30"
    window_end = "05:00"
    # Zero, because the panel in this VM has no input device at all and the Linux build
    # reports itself permanently idle (crates/app/src/update.rs says why). What is being
    # tested here is the *loop*; the idle rule itself is asserted in virtual time in
    # `castaway_update::policy`.
    idle_minutes = 0
    # Immediately, so the health marker and the version GC are observable inside a test
    # rather than five minutes into one.
    healthy_after_minutes = 0
  '';

  root = "/var/lib/castaway";
in
pkgs.testers.runNixOSTest {
  name = "castaway-update";

  nodes.receiver = { ... }: {
    virtualisation.memorySize = 2048;

    # UTC and no time sync, because the test moves the clock into the update window and a
    # daemon putting it back would be a flake nobody could reproduce.
    time.timeZone = "UTC";
    services.timesyncd.enable = false;

    environment.systemPackages = [ pkgs.jq ];

    # The launcher, exactly as the box will run it: one binary, one argument, and
    # everything else read off the tree beneath it.
    systemd.services.castaway-launcher = {
      description = "the castaway launcher";
      serviceConfig = {
        ExecStart = "${launcher}/bin/launcher --root ${root}";
        Environment = [
          "CASTAWAY_CONFIG=${config}"
          "HOME=/root"
        ];
        Restart = "no";
      };
    };
  };

  testScript = ''
    start_all()
    receiver.wait_for_unit("multi-user.target")

    with subtest("the install tree, with an update already staged and waiting"):
        receiver.succeed("mkdir -p ${root}/versions/${shaA} ${root}/versions/${shaB}")
        receiver.succeed(
            "install -m755 ${receiverA}/bin/castaway ${root}/versions/${shaA}/castaway"
        )
        receiver.succeed("printf '${shaA}\\n' > ${root}/current.txt")
        # The staged tree, as a completed download leaves it: under its final name, with
        # the manifest inside. Its provenance was checked when it was staged; rediscovery
        # trusts the tree on disk, which is the whole point of naming it only when complete.
        receiver.succeed(
            "install -m755 ${receiverB}/bin/castaway ${root}/versions/${shaB}/castaway"
        )
        receiver.succeed(
            "install -m644 ${stagedManifest}/manifest.json ${root}/versions/${shaB}/manifest.json"
        )

    with subtest("the clock is inside the shipped update window"):
        # 04:00, in the middle of the 03:30–05:00 window `Policy::default` ships. Moving
        # the panel to the window rather than the window to the panel is what makes this a
        # test of the constant that ships.
        receiver.succeed("date -s '04:00:00'")

    receiver.succeed("systemctl start castaway-launcher")
    # Not `log`: the test driver already has one of those, and shadowing it is a type
    # error rather than a mystery, which is the good outcome.
    LOG = "${root}/castaway.log"

    with subtest("the launcher starts the version current.txt names, and it arms"):
        receiver.wait_until_succeeds(f"grep -q 'auto-update is armed' {LOG}", timeout=120)
        # The build number reached the binary: without it the updater stands down as
        # `UnknownBuild` and nothing below could happen.
        receiver.succeed(f"grep -q 'build=${toString buildA}' {LOG}")

    with subtest("this version reports itself healthy, which is what stops a rollback"):
        receiver.wait_until_succeeds(
            "test -f ${root}/versions/${shaA}/.healthy", timeout=120
        )

    with subtest("the staged tree is rediscovered and ordered against what is running"):
        receiver.wait_until_succeeds(
            f"grep -q 'a staged update from an earlier night is still waiting' {LOG}",
            timeout=180,
        )

    with subtest("the panel is quiet, so it hands over to the launcher"):
        receiver.wait_until_succeeds(
            f"grep -q 'restarting into the new version' {LOG}", timeout=180
        )
        # The pointers moved together and in the right order: the new version is current,
        # and the one that was running is the rollback target.
        receiver.wait_until_succeeds(
            "test \"$(cat ${root}/current.txt)\" = ${shaB}", timeout=60
        )
        receiver.succeed("test \"$(cat ${root}/previous.txt)\" = ${shaA}")

    with subtest("the launcher notices the handshake and starts the new tree"):
        receiver.wait_until_succeeds(
            f"grep -q 'asked to be reloaded' {LOG}", timeout=120
        )
        receiver.wait_until_succeeds(
            f"grep -q 'now running version ${shortB}' {LOG}", timeout=120
        )
        # And the new one comes all the way up, which is the claim the whole exercise is
        # for: an unattended panel is running newer bits than it was, by itself.
        receiver.wait_until_succeeds(
            "test -f ${root}/versions/${shaB}/.healthy", timeout=180
        )

    with subtest("and it settles: nothing further is staged, and the way back is kept"):
        # The new version finds no *newer* tree to rediscover — the one it replaced is
        # older — so it stops rather than looping. With no reachable release API it also
        # reports that it took nothing, which is the correct kiosk answer and is what the
        # panel would log every night the network was down.
        receiver.wait_until_succeeds(
            f"grep -q 'nothing taken tonight' {LOG}", timeout=300
        )
        # The rollback target survives the version GC — a panel with nothing to fall back
        # to is the state this whole design exists to avoid.
        receiver.succeed("test -d ${root}/versions/${shaA}")
        receiver.succeed("test \"$(cat ${root}/previous.txt)\" = ${shaA}")
  '';
}
