# Bind a USB device to WinUSB so castaway's own HCI stack can claim it.
#
# This is what Zadig does, with in-box tools instead. Zadig is not required and neither is
# test-signing mode: the kernel driver (winusb.sys) is already Microsoft-signed, and the
# only thing our package contributes is an INF. What Windows wants is a catalog whose
# signature chains to a trusted publisher -- so we mint a self-signed code-signing cert,
# trust it, catalog the INF with New-FileCatalog, sign the catalog, and install.
#
#   -Undo   remove the binding and hand the radio back to Windows' own stack.
#
# Reversal matters here: this takes the Bluetooth radio away from Windows entirely. On the
# panel that is the point, but on a machine someone also uses it is rude, and the way back
# should not require knowing what was done.
param(
  [string]$HardwareId = 'USB\VID_8087&PID_0033',
  [string]$DeviceName = 'Bluetooth controller (castaway WinUSB)',
  [switch]$Undo
)

$ErrorActionPreference = 'Stop'
$ProviderName = 'castaway'
$work = Join-Path $env:TEMP 'castaway-winusb'
$infName = 'castaway-winusb.inf'
$catName = 'castaway-winusb.cat'

function Say($m) { Write-Output ("==> " + $m) }

# The device instance actually present, as opposed to the hardware ID pattern.
function Get-Target {
  Get-PnpDevice -PresentOnly -ErrorAction SilentlyContinue | Where-Object {
    $hw = (Get-PnpDeviceProperty -InstanceId $_.InstanceId -KeyName 'DEVPKEY_Device_HardwareIds' -ErrorAction SilentlyContinue).Data
    $hw -and ($hw -contains $HardwareId)
  }
}

function Show-State($label) {
  Say $label
  foreach ($d in Get-Target) {
    $svc = (Get-PnpDeviceProperty -InstanceId $d.InstanceId -KeyName 'DEVPKEY_Device_Service' -ErrorAction SilentlyContinue).Data
    $inf = (Get-PnpDeviceProperty -InstanceId $d.InstanceId -KeyName 'DEVPKEY_Device_DriverInfPath' -ErrorAction SilentlyContinue).Data
    Write-Output ("    {0}  status={1}  service={2}  inf={3}" -f $d.InstanceId, $d.Status, $svc, $inf)
  }
}

if ($Undo) {
  Show-State "before undo"
  # Delete our package; Windows re-evaluates and the inbox driver wins again.
  $installed = (pnputil /enum-drivers) -join "`n"
  $blocks = $installed -split "`r?`n`r?`n"
  foreach ($b in $blocks) {
    if ($b -match 'castaway-winusb\.inf' -and $b -match 'Published Name\s*:\s*(oem\d+\.inf)') {
      $oem = $Matches[1]
      Say "deleting driver package $oem"
      pnputil /delete-driver $oem /uninstall /force | ForEach-Object { Write-Output ("    " + $_) }
    }
  }
  foreach ($d in Get-Target) { pnputil /restart-device $d.InstanceId | Out-Null }
  Start-Sleep -Seconds 3
  Show-State "after undo"
  Say "if the radio is still not back, Device Manager -> the device -> Driver -> Roll Back / Update, or a reboot"
  exit 0
}

$target = Get-Target
if (-not $target) { throw "no present device matches $HardwareId" }
Show-State "before"

# --- 1. the INF -------------------------------------------------------------------------
# `Include`/`Needs` against the inbox winusb.inf rather than copying any binary: the package
# carries no files of its own, which is what keeps it installable without shipping a driver.
New-Item -ItemType Directory -Force -Path $work | Out-Null
Get-ChildItem $work -File -ErrorAction SilentlyContinue | Remove-Item -Force
# A stable per-device interface GUID. WinUSB exposes the device under this, and nusb finds
# it by VID/PID rather than by GUID -- but WinUSB will not surface the device without one.
$ifaceGuid = '{a5dcbf10-6530-11d2-901f-00c04fb951ed}'
$infPath = Join-Path $work $infName
@"
; Generated by castaway. Binds $HardwareId to WinUSB so the receiver's own HCI stack can
; claim it. Windows' Bluetooth stack will not see this radio while this is installed.
[Version]
Signature   = "`$Windows NT`$"
Class       = USBDevice
ClassGuid   = {88BAE032-5A81-49f0-BC3D-A4FF138216D6}
Provider    = %ProviderName%
CatalogFile = $catName
DriverVer   = 01/01/2026,1.0.0.0
PnpLockdown = 1

[Manufacturer]
%ProviderName% = Standard,NTamd64

[Standard.NTamd64]
%DeviceName% = USB_Install, $HardwareId

[USB_Install]
Include = winusb.inf
Needs   = WINUSB.NT

[USB_Install.Services]
Include = winusb.inf
Needs   = WINUSB.NT.Services

[USB_Install.HW]
AddReg = Dev_AddReg

[Dev_AddReg]
HKR,,DeviceInterfaceGUIDs,0x10000,"$ifaceGuid"

[Strings]
ProviderName = "$ProviderName"
DeviceName   = "$DeviceName"
"@ | Set-Content -Path $infPath -Encoding Ascii
Say "wrote $infPath"

# --- 2. a cert Windows will trust for driver packages ------------------------------------
$subject = 'CN=castaway WinUSB (self-signed, driver package only)'
$cert = Get-ChildItem Cert:\LocalMachine\My -ErrorAction SilentlyContinue |
  Where-Object { $_.Subject -eq $subject -and $_.NotAfter -gt (Get-Date) } | Select-Object -First 1
if (-not $cert) {
  Say "minting a self-signed code-signing certificate"
  $cert = New-SelfSignedCertificate -Type CodeSigningCert -Subject $subject `
            -CertStoreLocation Cert:\LocalMachine\My -NotAfter (Get-Date).AddYears(5)
} else {
  Say "reusing the existing certificate $($cert.Thumbprint)"
}
# Root so the chain validates; TrustedPublisher so installation is not prompted.
$tmpCer = Join-Path $work 'castaway.cer'
Export-Certificate -Cert $cert -FilePath $tmpCer | Out-Null
foreach ($store in @('Root', 'TrustedPublisher')) {
  Import-Certificate -FilePath $tmpCer -CertStoreLocation ("Cert:\LocalMachine\" + $store) | Out-Null
  Say "trusted in LocalMachine\$store"
}
Remove-Item $tmpCer -Force

# --- 3. catalog it and sign ---------------------------------------------------------------
$catPath = Join-Path $work $catName
New-FileCatalog -Path $work -CatalogFilePath $catPath -CatalogVersion 2 | Out-Null
$sig = Set-AuthenticodeSignature -FilePath $catPath -Certificate $cert `
        -TimestampServer $null -HashAlgorithm SHA256
Say ("catalog signature: " + $sig.Status)
if ($sig.Status -ne 'Valid') { throw "catalog did not sign cleanly: $($sig.StatusMessage)" }

# --- 4. install and bind ------------------------------------------------------------------
Say "installing the driver package"
pnputil /add-driver $infPath /install | ForEach-Object { Write-Output ("    " + $_) }

# `/install` applies the package to matching devices, but the inbox driver can still win on
# rank. Restarting the device makes Windows re-run the match with our package present.
foreach ($d in Get-Target) {
  Say ("restarting " + $d.InstanceId)
  pnputil /restart-device $d.InstanceId | ForEach-Object { Write-Output ("    " + $_) }
}
Start-Sleep -Seconds 5
Show-State "after"

$svc = foreach ($d in Get-Target) {
  (Get-PnpDeviceProperty -InstanceId $d.InstanceId -KeyName 'DEVPKEY_Device_Service' -ErrorAction SilentlyContinue).Data
}
if ($svc -contains 'WinUSB') {
  Say "SUCCESS: the radio is on WinUSB"
} else {
  Say "NOT YET on WinUSB (service=$svc) -- the inbox driver still outranks ours"
  Say "next lever: pnputil /add-driver ... /install /force, or Device Manager -> Update Driver -> Browse -> Let me pick"
  exit 1
}
