//! # fcast-flatbuf
//!
//! The FlatBuffers message types for FCast protocol v4 (#248), generated by
//! `flatc` 25.12.19 from `schema/fcast.fbs` — the schema vendored verbatim from
//! the published spec (FUTO's FCast repository @ f22f72dc, MIT).
//!
//! This is a bindings crate in the `ldac-sys`/`moonlight-sys` mold: the generated
//! code carries the generator's own `unsafe` (buffer accessors behind the
//! verifier), which is why it lives here and not in `proto-fcast` — that crate is
//! `forbid(unsafe_code)` (ground rule 8) and consumes only the safe, verified
//! surface: [`root_as_packet`] and the typed accessors it yields.
//!
//! Regenerate with `flatc --rust -o <out> schema/fcast.fbs` (nixpkgs
//! `flatbuffers`); the output is checked in and drift-checked the same way the
//! other bindings crates are. At the pinned versions the output is byte-identical
//! to the reference implementation's own checked-in codegen, which was verified
//! once at vendoring time.

// The generated module is the whole crate; the generator's lint hygiene is not
// ours to fix, and the workspace lints stay on for this wrapper file itself.
// `unsafe_code` is allowed for the same reason the -sys crates allow it (ground
// rule 8): the unsafe is the generator's, behind the verifier, and this crate's
// job is to quarantine it.
#[allow(
    unsafe_code,
    unused_imports,
    clippy::all,
    clippy::pedantic,
    // The generated accessors unwrap fields the verifier already proved present
    // (`(required)` in the schema); rule 7's unwrap ban is about unproven paths.
    clippy::unwrap_used,
    mismatched_lifetime_syntaxes
)]
mod generated;

pub use generated::fcast::v4 as flat;

/// The v4 packet ceiling: 512 KiB of opcode + body.
pub const MAX_PACKET_SIZE: usize = 512 * 1024;

/// Parse and fully verify a `Flatbuf` packet body as the schema's root table.
///
/// # Errors
/// [`flatbuffers::InvalidFlatbuffer`] when the buffer fails verification — the
/// reference receiver treats that as a session-fatal fault, and so do we.
pub fn root_as_packet(body: &[u8]) -> Result<flat::Packet<'_>, flatbuffers::InvalidFlatbuffer> {
    flat::root_as_packet(body)
}

/// Re-export for builder use in `proto-fcast` (constructing outbound messages is
/// entirely safe API).
pub use flatbuffers::{FlatBufferBuilder, WIPOffset};
