//! Differential test: our receiver against openscreen's packetizer.
//!
//! `tests/fixtures/rtp-stream/` holds a Cast RTP stream generated by openscreen's own
//! `RtpPacketizer` and `FrameCrypto`, plus the plaintext frames it was made from. If
//! `proto_cast` reassembles and decrypts those datagrams back into those frames, then
//! our framing, our truncated-id expansion, and our per-frame IV derivation all agree
//! with the implementation Chromecasts actually talk to.
//!
//! A round-trip against our own serializer would prove none of that — it would only
//! show our encoder and decoder sharing a misunderstanding.
//!
//! This exercises the pure core directly. `mirror_udp.rs` pushes the same bytes through
//! the socket actor.

#![allow(clippy::unwrap_used)]

mod common;

use common::{config, datagrams, expected_frames, ExpectedFrame, RECEIVER_SSRC, SENDER_SSRC};
use proto_cast::mirror::crypt_frame;
use proto_cast::receiver::{CastRtpReceiver, Consume, Received};
use proto_cast::rtp::{FrameId, NackTarget};

/// Drain everything the receiver is willing to hand over, decrypting as we go.
fn drain(rx: &mut CastRtpReceiver) -> Vec<ExpectedFrame> {
    let cfg = config();
    let mut out = Vec::new();
    while let Some(delivered) = rx.next_frame(Consume::InOrder) {
        let header = delivered.frame.header;
        let plaintext = crypt_frame(&cfg, header.frame_id, &delivered.frame.payload).unwrap();
        out.push(ExpectedFrame {
            dependency: header.dependency,
            frame_id: header.frame_id.value(),
            referenced_frame_id: header.referenced_frame_id.value(),
            rtp_timestamp: header.rtp_timestamp.value(),
            new_playout_delay_ms: header.new_playout_delay_ms.unwrap_or(0),
            payload: plaintext,
        });
    }
    out
}

#[test]
fn the_stream_reassembles_and_decrypts_to_the_frames_openscreen_encoded() {
    let mut rx = CastRtpReceiver::new(SENDER_SSRC, RECEIVER_SSRC);
    for datagram in datagrams() {
        let outcome = rx.receive(&datagram).unwrap();
        assert!(
            matches!(outcome, Received::Progress(_) | Received::FrameComplete(_)),
            "openscreen emitted a packet we would have dropped: {outcome:?}"
        );
    }

    let got = drain(&mut rx);
    let want = expected_frames();
    assert_eq!(got.len(), want.len(), "frame count");
    for (got, want) in got.iter().zip(want.iter()) {
        assert_eq!(got.frame_id, want.frame_id);
        assert_eq!(got.dependency, want.dependency, "frame {}", want.frame_id);
        assert_eq!(
            got.referenced_frame_id, want.referenced_frame_id,
            "frame {}",
            want.frame_id
        );
        assert_eq!(
            got.rtp_timestamp, want.rtp_timestamp,
            "frame {}",
            want.frame_id
        );
        assert_eq!(
            got.new_playout_delay_ms, want.new_playout_delay_ms,
            "frame {}",
            want.frame_id
        );
        assert_eq!(
            got.payload.len(),
            want.payload.len(),
            "frame {} payload length",
            want.frame_id
        );
        assert!(
            got.payload == want.payload,
            "frame {} decrypted to the wrong bytes — the per-frame IV or the \
             packet ordering disagrees with openscreen",
            want.frame_id
        );
    }
}

#[test]
fn reversing_every_frames_packets_changes_nothing() {
    // Reassembly must depend on packet ids, not arrival order. Reversing the whole
    // stream also puts each frame's packet 0 — the only one carrying the metadata —
    // last, so the collector cannot be relying on seeing it first.
    let mut rx = CastRtpReceiver::new(SENDER_SSRC, RECEIVER_SSRC);
    for datagram in datagrams().into_iter().rev() {
        rx.receive(&datagram).unwrap();
    }
    assert_eq!(drain(&mut rx), expected_frames());
}

#[test]
fn a_lost_packet_is_nacked_by_name_and_recovered_on_retransmission() {
    let all = datagrams();
    let mut rx = CastRtpReceiver::new(SENDER_SSRC, RECEIVER_SSRC);

    // Frame 0 is one packet; frame 1 is several. Drop one packet in the middle of
    // frame 1 and hold it back, as a lossy link would.
    let held = all[2].clone();
    for (index, datagram) in all.iter().enumerate() {
        if index == 2 {
            continue;
        }
        rx.receive(datagram).unwrap();
    }

    // Only frame 0 can be delivered; frame 1 is still short a packet.
    assert_eq!(drain(&mut rx).len(), 1);

    let feedback = rx.feedback(None);
    assert_eq!(feedback.checkpoint, FrameId::first());
    assert_eq!(
        feedback.nacks.len(),
        1,
        "exactly one packet is missing, so exactly one NACK: {:?}",
        feedback.nacks
    );
    assert_eq!(feedback.nacks[0].frame_id, FrameId::new(1));
    assert_eq!(
        feedback.nacks[0].target,
        NackTarget::Packet(proto_cast::rtp::PacketId::new(1).unwrap()),
        "the NACK must name the packet we are actually missing"
    );
    assert!(
        feedback.acks.contains(&FrameId::new(2)),
        "frames that arrived after the hole must still be ACKed, or the sender \
         will resend them too: {:?}",
        feedback.acks
    );

    // The sender retransmits, and the rest of the stream falls out intact.
    rx.receive(&held).unwrap();
    let recovered = drain(&mut rx);
    assert_eq!(recovered, expected_frames()[1..]);
}

#[test]
fn the_feedback_for_this_stream_serializes_within_one_datagram() {
    // Worst case for us: every frame present but the very first packet missing, so
    // nothing can be delivered and the ACK vector spans the whole window.
    let mut rx = CastRtpReceiver::new(SENDER_SSRC, RECEIVER_SSRC);
    for datagram in datagrams().into_iter().skip(1) {
        rx.receive(&datagram).unwrap();
    }

    let feedback = rx.feedback(Some(0x0102_0304_0506_0708));
    let (packet, report) = proto_cast::rtcp::build(&feedback, 1472);
    assert!(packet.len() <= 1472);
    assert_eq!(packet.len() % 4, 0, "RTCP packets are 32-bit word aligned");
    assert_eq!(report.nacks_dropped, 0);
    assert_eq!(report.acks_dropped, 0);
}
