//! Generates the checked-in LDAC test vectors, using Sony's own encoder as the oracle.
//!
//! Run it from the repo root with the feature that binds the library:
//!
//! ```text
//! cargo run -p pipeline --features ldac --example ldac_fixtures
//! ```
//!
//! It writes two files per configuration, and they are two views of the same bytes:
//!
//! - `crates/proto-bluetooth-audio/tests/fixtures/a2dp-ldac-<rate>-<mode>.bin` — whole
//!   A2DP media packets, RTP header and one-byte payload header included. This is what
//!   comes off an L2CAP media channel, and it is what [`Depacketizer`] is tested against.
//! - `crates/pipeline/tests/fixtures/ldac-<rate>-<mode>.bin` — the same packets with
//!   those thirteen bytes removed, i.e. the bare `ldac_transport_frame` sequences a
//!   decoder is handed. This is what the decode test replays.
//!
//! Both use the repo's usual length-prefixed record framing: a little-endian `u32` length
//! followed by that many bytes, repeated. Same as `CASTAWAY_DUMP_AUDIO` writes, so a
//! capture from a real phone drops straight in beside these.
//!
//! # Why an encoder we also decode with
//!
//! Rule 9 wants fixtures captured from real senders, and these are not that — they are
//! generated by the same library that decodes them, which cannot prove interoperability
//! on its own. What they *do* prove is everything between the wire and the decoder, and
//! they do it in a way a phone cannot: the encoder reports how many transport frames it
//! packed into each packet and what rate it coded them at, so the checked-in bytes come
//! with ground truth attached. `proto_bluetooth_audio::ldac` then walks those bytes with a
//! pure Rust parser that shares no code with the library, and the two are asserted to
//! agree. A capture from an Android phone would strengthen the interop claim and is worth
//! adding when one is to hand; it would not replace this, because a capture does not come
//! with the frame counts.
//!
//! The RTP header here is written by hand rather than through `substrate-rtp`, for the
//! same reason: a fixture assembled by the code under test proves less than one that was
//! not.
//!
//! [`Depacketizer`]: proto_bluetooth_audio::media::Depacketizer

// A generator, not library code: it drives the encoder directly rather than through a safe
// wrapper, because the receiver has no reason to own one. Every block still carries its
// invariant (ground rule 8).
#![allow(unsafe_code)]

use std::io::Write as _;
use std::path::{Path, PathBuf};

use ldac_sys as ldac;

/// Encoder quality. MQ — 303/330 kbps — because these fixtures live in git: HQ would
/// triple them for audio that is thrown away after an RMS check. The frame *lengths* MQ
/// produces are still per-frame variable, which is the property the walk cares about.
const EQMID: i32 = 2;

/// The MTU an LDAC sender optimises for: the header calls 679 bytes the minimum an L2CAP
/// implementation for LDAC has to support, because LDAC targets the 2-DH5 packet.
const MTU: i32 = 679;

/// Dynamic payload type. A2DP does not assign one, so senders pick from the dynamic
/// range; the depacketizer does not care what it is, which is worth having a fixture prove.
const PAYLOAD_TYPE: u8 = 96;

/// One configuration to generate.
struct Config {
    rate: u32,
    /// The A2DP channel *mode* bitfield — `LDACBT_CHANNEL_MODE_*`, not the `LDAC_CCI_*`
    /// numbering. Passing the wrong one fails init rather than mis-encoding, but only
    /// because the library asserts on it.
    channel_mode: u32,
    name: &'static str,
    /// How much audio to encode, in PCM frames. Kept short: these are checked into the
    /// repository, and at 303 kbps a second of LDAC is 38 KB.
    frames: usize,
    /// Switch encoder quality every this many encode calls, cycling HQ → SQ → MQ.
    ///
    /// `None` for a fixed-bitrate stream, which is what every other fixture here is and
    /// what no real LDAC sender is.
    switch_every: Option<usize>,
}

fn main() {
    let root = repo_root();
    let configs = [
        Config {
            rate: 44_100,
            channel_mode: ldac::LDACBT_CHANNEL_MODE_STEREO,
            name: "44100-stereo",
            frames: 11_025, // a quarter second
            switch_every: None,
        },
        // The other half of the format space: 96 kHz puts 256 samples in a frame instead
        // of 128, and dual channel codes two channels independently. A fixture set that
        // was all 44.1 kHz stereo would leave both of those untested, and 96 kHz is
        // exactly where a rate assumed rather than read goes wrong (#70).
        Config {
            rate: 96_000,
            channel_mode: ldac::LDACBT_CHANNEL_MODE_DUAL_CHANNEL,
            name: "96000-dual",
            frames: 12_000, // an eighth of a second, and the same frame count
            switch_every: None,
        },
        // Mono, because it is the one configuration whose block size differs — 128 samples
        // rather than 256 for a stereo frame — and therefore the one that catches a decoder
        // labelling its output with the negotiated channel count instead of the stream's.
        Config {
            rate: 44_100,
            channel_mode: ldac::LDACBT_CHANNEL_MODE_MONO,
            name: "44100-mono",
            frames: 11_025,
            switch_every: None,
        },
        // Adaptive bitrate: the same stream, coded at a quality that keeps changing. This
        // is the only fixture here that resembles what a phone actually sends — LDAC's
        // headline feature is that it drops between 990, 660 and 330 kbps as the 2.4 GHz
        // band gets busy, and on a hackerspace wall it will be doing that constantly.
        //
        // It matters because the frame length is *in the frame header*, so every step
        // disagrees with the handle's configuration and re-initialises the decoder. The
        // library reports that as failure — `-1` with `LDACBT_ERR_DEC_CONFIG_UPDATED` —
        // having already decoded the frame, so a wrapper that believes the return code
        // loses the first frame of every change. Nothing here had ever decoded such a
        // stream (#14).
        Config {
            rate: 44_100,
            channel_mode: ldac::LDACBT_CHANNEL_MODE_STEREO,
            name: "44100-stereo-adaptive",
            frames: 11_025,
            switch_every: Some(8),
        },
    ];

    for config in &configs {
        let packets = encode(config);
        assert!(!packets.is_empty(), "{} produced nothing", config.name);

        let a2dp = root
            .join("crates/proto-bluetooth-audio/tests/fixtures")
            .join(format!("a2dp-ldac-{}.bin", config.name));
        let bare = root
            .join("crates/pipeline/tests/fixtures")
            .join(format!("ldac-{}.bin", config.name));

        write_records(&a2dp, packets.iter().map(|p| p.a2dp.as_slice()));
        write_records(&bare, packets.iter().map(|p| p.frames.as_slice()));

        let frames: u32 = packets.iter().map(|p| u32::from(p.frame_count)).sum();
        let bytes: usize = packets.iter().map(|p| p.frames.len()).sum();
        println!(
            "{}: {} packets, {frames} transport frames, {bytes} bytes of bitstream",
            config.name,
            packets.len(),
        );
        println!(
            "  ground truth for the tests: packets={}, frames={frames}",
            packets.len()
        );
    }
}

/// One A2DP media packet and the pieces the fixtures split it into.
struct Packet {
    /// RTP header + payload header + transport frames.
    a2dp: Vec<u8>,
    /// The transport frames alone.
    frames: Vec<u8>,
    /// How many transport frames the *encoder* said it packed in — the number the pure
    /// parser's walk is checked against.
    frame_count: u8,
}

/// Encode a 440 Hz sine into A2DP media packets.
fn encode(config: &Config) -> Vec<Packet> {
    let channels = if config.channel_mode == ldac::LDACBT_CHANNEL_MODE_MONO {
        1usize
    } else {
        2
    };

    // SAFETY: `ldacBT_get_handle` allocates and owns nothing of ours; the handle is freed
    // on every path out of this function. This is a generator, not library code — the
    // safe wrapper is `pipeline::ldac_decode`, and it deliberately does not wrap the
    // encoder because the receiver never encodes.
    let handle = unsafe { ldac::ldacBT_get_handle() };
    assert!(!handle.is_null(), "could not allocate an LDAC handle");

    // SAFETY: `handle` is a freshly allocated handle we exclusively own. `cm` is one of
    // the three channel modes the library asserts on, `sf` a supported rate, and the
    // sample format matches the `i16` buffers fed to `ldacBT_encode` below.
    let rc = unsafe {
        ldac::ldacBT_init_handle_encode(
            handle,
            MTU,
            EQMID,
            i32::try_from(config.channel_mode).expect("channel mode fits"),
            ldac::LDACBT_SMPL_FMT_T::LDACBT_SMPL_FMT_S16,
            i32::try_from(config.rate).expect("rate fits"),
        )
    };
    assert_eq!(rc, 0, "encoder init failed for {}", config.name);

    // Input is fixed at 128 samples per channel per call, whatever the sample rate.
    let chunk = ldac::LDACBT_ENC_LSU as usize;
    let pcm = sine(config.rate, config.frames, channels);

    let mut packets = Vec::new();
    let mut sequence: u16 = 0;
    let mut timestamp: u32 = 0;
    let mut stream = vec![0u8; ldac::LDACBT_MAX_NBYTES as usize];
    // Cycled rather than random so the fixture is reproducible byte for byte: a generator
    // whose output moved would make every regeneration a diff nobody could review.
    const QUALITIES: [u32; 3] = [
        ldac::LDACBT_EQMID_HQ,
        ldac::LDACBT_EQMID_SQ,
        ldac::LDACBT_EQMID_MQ,
    ];

    for (call, block) in pcm.chunks(chunk * channels).enumerate() {
        if let Some(every) = config.switch_every {
            if call > 0 && call % every == 0 {
                let quality = QUALITIES[(call / every) % QUALITIES.len()];
                // SAFETY: `handle` is initialised for encode and exclusively ours;
                // `quality` is one of the three `LDACBT_EQMID_*` values the library
                // accepts. This only changes the encoder's target bitrate.
                let rc = unsafe {
                    ldac::ldacBT_set_eqmid(handle, i32::try_from(quality).expect("eqmid fits"))
                };
                assert_eq!(rc, 0, "could not change quality for {}", config.name);
            }
        }
        // The library requires a full block and zero-fill for the remainder.
        let mut input = vec![0i16; chunk * channels];
        input[..block.len()].copy_from_slice(block);

        let mut pcm_used = 0i32;
        let mut stream_sz = 0i32;
        let mut frame_num = 0i32;
        // SAFETY: `handle` is initialised for encode. `input` holds exactly
        // `LDACBT_ENC_LSU * channels` i16 samples, which is the block size the encoder
        // was configured for, and `stream` is `LDACBT_MAX_NBYTES` bytes — the maximum
        // size of a transport-frame sequence, which is what bounds the write. The three
        // out-parameters are live locals.
        let rc = unsafe {
            ldac::ldacBT_encode(
                handle,
                input.as_mut_ptr().cast(),
                &raw mut pcm_used,
                stream.as_mut_ptr(),
                &raw mut stream_sz,
                &raw mut frame_num,
            )
        };
        assert_eq!(rc, 0, "encode failed for {}", config.name);

        // Output appears only every few calls — the encoder fills an MTU before emitting.
        let wrote = usize::try_from(stream_sz).unwrap_or(0);
        if wrote > 0 {
            let frames = stream[..wrote].to_vec();
            let frame_count = u8::try_from(frame_num).expect("frame count fits a byte");
            packets.push(Packet {
                a2dp: a2dp_packet(sequence, timestamp, frame_count, &frames),
                frames,
                frame_count,
            });
            sequence = sequence.wrapping_add(1);
        }
        // The RTP timestamp advances by PCM frames, not by packets: it is a sample clock.
        timestamp = timestamp.wrapping_add(u32::try_from(block.len() / channels).unwrap_or(0));
    }

    // SAFETY: `handle` was initialised for encode and is not used after this.
    unsafe { ldac::ldacBT_free_handle(handle) };
    packets
}

/// Wrap a transport-frame sequence in the framing an A2DP media channel carries.
///
/// Twelve bytes of RTP and then one byte whose value is the frame count. That byte is why
/// the depacketizer strips one byte for LDAC; the fixture exists partly so that a change
/// which stops stripping it fails on real bytes rather than on a hand-written stub.
fn a2dp_packet(sequence: u16, timestamp: u32, frame_count: u8, frames: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(13 + frames.len());
    out.push(0x80); // version 2, no padding, no extension, no CSRCs
    out.push(PAYLOAD_TYPE); // no marker bit
    out.extend_from_slice(&sequence.to_be_bytes());
    out.extend_from_slice(&timestamp.to_be_bytes());
    out.extend_from_slice(&0xDEAD_BEEFu32.to_be_bytes()); // SSRC
    out.push(frame_count);
    out.extend_from_slice(frames);
    out
}

/// The sample rate as a float, for the sine.
fn f64_rate(rate: u32) -> f32 {
    // Every rate LDAC codes is exact in f32; `as` here would be a lossy-cast warning for a
    // conversion that cannot lose anything.
    f32::from(u16::try_from(rate / 10).unwrap_or(4410)) * 10.0
}

/// A 440 Hz sine, interleaved, at three quarters of full scale.
fn sine(rate: u32, frames: usize, channels: usize) -> Vec<i16> {
    let mut out = Vec::with_capacity(frames * channels);
    let rate = f64_rate(rate);
    for n in 0..frames {
        let t = f32::from(u16::try_from(n).unwrap_or(u16::MAX)) / rate;
        // Three quarters of full scale: loud enough that a decode at half amplitude is
        // outside the test's window, quiet enough that nothing clips into it.
        let level = (t * 440.0 * std::f32::consts::TAU).sin() * 24_000.0;
        #[allow(clippy::cast_possible_truncation)]
        let s = level as i16;
        for _ in 0..channels {
            out.push(s);
        }
    }
    out
}

/// Write length-prefixed records.
fn write_records<'a>(path: &Path, records: impl Iterator<Item = &'a [u8]>) {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("fixture directory");
    }
    let mut file = std::fs::File::create(path).expect("fixture file");
    for record in records {
        let len = u32::try_from(record.len()).expect("record length fits");
        file.write_all(&len.to_le_bytes()).expect("write length");
        file.write_all(record).expect("write record");
    }
    println!("wrote {}", path.display());
}

/// The repo root, from this crate's manifest directory.
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("crates/pipeline is two levels below the root")
        .to_path_buf()
}
